---
apiVersion: batch/v1
kind: Job
metadata:
  name: rhoai-gpu-updater
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: rhoai-gpu-updater
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
        name: rhoai-gpu-updater
        command:
        - /bin/bash
        args:
        - -c
        - |
          while true
          do
            echo "Checking if nvidia-operator-validator pod exists..."

            oc get pods -n nvidia-gpu-operator | grep nvidia-operator-validator
            if [[ $? -eq '0' ]]; then
              echo "Found! Breaking loop"
              break
            fi
            sleep 5s
          done

          export VALIDATOR_POD=`oc get pods -n nvidia-gpu-operator | grep nvidia-operator-validator | awk '{ print $1 }'`

          until [`oc get pods -n nvidia-gpu-operator ${VALIDATOR_POD} -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}'` -ne "True"]
          do
            echo "Waiting for Pod ${VALIDATOR_POD} to be Ready..."
            sleep 5s
          done

          echo "${VALIDATOR_POD} Ready, deleting migration-gpu-status cm and restarting dashboard Pods"

          oc delete cm -n redhat-ods-applications migration-gpu-status
          oc delete pods -n redhat-ods-applications -l app.opendatahub.io/rhods-dashboard=true
