---
apiVersion: batch/v1
kind: Job
metadata:
  name: rhoai-gpu-updater
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: rhoai-gpu-updater
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
        name: rhoai-gpu-updater
        command:
        - /bin/bash
        args:
        - -c
        - |
          export VALIDATOR_POD=`oc get pods -n nvidia-gpu-operator | grep nvidia-operator-validator | awk '{ print $1 }'`
          oc wait -n nvidia-gpu-operator --for=condition=Ready pod/${VALIDATOR_POD} --timeout=-1s
          oc delete cm -n redhat-ods-applications migration-gpu-status
          oc delete pods -n redhat-ods-applications -l app.opendatahub.io/rhods-dashboard=true
