---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-pod
  namespace: nvidia-gpu-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
