---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vew-pod-rhoai-gpu-updater-sa
  namespace: nvidia-gpu-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view-pod
subjects:
- kind: ServiceAccount
  name: rhoai-gpu-updater
  namespace: nvidia-gpu-operator
