---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rhoai-delete-pod-cm-rhoai-gpu-updater-sa
  namespace: redhat-ods-applications
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rhoai-delete-pod-cm
subjects:
- kind: ServiceAccount
  name: rhoai-gpu-updater
  namespace: nvidia-gpu-operator
