apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rhoai-delete-pod-cm
  namespace: redhat-ods-applications
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  verbs:
  - get
  - list
  - delete
  - watch
